python3 hyperopt_for_individual_emotion.py 0
python3 hyperopt_for_individual_emotion.py 1
python3 hyperopt_for_individual_emotion.py 2
python3 hyperopt_for_individual_emotion.py 3
python3 hyperopt_for_individual_emotion.py 4
python3 hyperopt_for_individual_emotion.py 5
python3 hyperopt_for_individual_emotion.py 6 
